dist: trusty
os: linux

git:
  depth: 150

env:
  global:
  - CACHE_DIR="$HOME/misc_cache"
  - MINICONDA_DIR="$HOME/miniconda"
  - PIP_DIR="$HOME/virtualenv"
  - GATK_PATH="$CACHE_DIR"
  - PYTHONIOENCODING=UTF8
  - PYTEST_ADDOPTS="-rsxX -n 2 --durations=25 --fixture-durations=10 --junit-xml=pytest.xml --cov-report= --cov broad_utils --cov illumina --cov assembly --cov interhost --cov intrahost --cov metagenomics --cov ncbi --cov read_utils --cov kmer_utils --cov reports --cov taxon_filter --cov tools --cov util --cov file_utils"
  
  - DOCKER_REGISTRY="quay.io"
  - DOCKER_REPO_PROD="quay.io/ilya_broad/cms"
  - DOCKER_REPO_DEV="quay.io/ilya_broad/cms-dev"
  
#  - DOCKER_REGISTRY_MIRROR="docker.io"
#  - DOCKER_REPO_PROD_MIRROR="notestaff/cms"
  
  - BOTO_CONFIG=/dev/null # bogus value to override config on travis
  - _JAVA_OPTIONS="-Xmx3g" # overrides jvm opts set elsewhere; see: https://stackoverflow.com/questions/28327620/difference-between-java-options-java-tool-options-and-java-opts

cache:
  directories:
    - $HOME/misc_cache
    - $HOME/miniconda
  timeout: 1000

#stages:
#  - build
#  - test

jobs:
  fast_finish: true
  include:

    - language: java
      jdk: openjdk8
      sudo: required
      addons:
        apt:
          packages:
          - docker-ce
      env:
        - TRAVIS_JOB=docker_wdl
        # DOCKER_USER (for Quay.io)
        - secure: "hvGlBGrUOXbFvFwEIKLGjLBhKfI0XYlLLGPgBhP0hwo2LynpJMgUAVhUR2FQYl/NrTWASW5dq4Bku7VeBc4ezJJvVsk2o3B3afc55pQeXWltHp6ICnXOMwlWzcEnOSIxXGG+MGJBCHMoeRSYK4JY5qYSOzxKGt8IfFLokGIMkKE="
        # DOCKER_PASS (for Quay.io)
        - secure: "O39t8WLEowJ2XyiNRXj0GrJbGH9KfsQrqgiQ1P5sKyrDIIvqJFcm6bAfXdPDoeGvO8QWeVrKSMyE26L/MAHRqTjBcJ9GbsUDnmFdZneRAXwLAGzou8GN1tjVSdrsIdaIJQxc5b1P9JFwR+pwG8XCy9Gbix5GCgh8f6A/Biut8ck="
        ## DOCKER_USER_MIRROR (for DockerHub)
        - secure: "hOFMwRq7RDqNc906UhEkCgme6X6UJlXKRv5OY1H3xcZ4DP4jcPFQ53UYko9tZaEVcTTEmKi+ouw8wqdsa4FyqcVQNvkZWl5/kCtuLDNOkR15N3JsS1b5LhMzTzddmCDzMf/JgW3X9IvoZjcTagq47IdHPWhsFIT5/biWBf0lv+s="
        ## DOCKER_PASS_MIRROR (for DockerHub)
        - secure: "as2LJIEipIC2X1JkBV42q/BkNKstriAuyWgKSjE+PwufFMZWtIeap6r3/3HVq/gN0ilztjWNxuKec+kx4MCPIXMognAAFdAKgdi/inz8bNSBTCflDyB88tb1z0Y/ThdJ5sgl6d0b7QXXj9F6QFj/R7uRGtt9dMwnwjjf3Ol2nCE="
        # DX_API_TOKEN (for DNAnexus builds)
        - secure: "bYTo93BqQQ11Zs7tXE40fBGC6CXSRpkCZ9Q8lvTFjTd1P4q+iDWGtKovd19WobHkiCeS3UgIhamTFH5/8G+q8CiDmnCCjJtj7Y6KQDbQRZbDoUAU7uU26L+V0RLDUWJXl2mo8B6jQYTdqiJ6QEcUlOkGZw+IEh+68BWSe82W8Kc="
        - DX_PROJECT=project-FkvVj7j098bk0461KXGQg3Z5
      install:
        #- travis/upgrade-docker.sh
        - travis/install-wdl.sh
        - travis/install-gatk.sh
      script:
        - set -e
        # pull old docker image
        - if [ -f "$CACHE_DIR/old-docker-tag.txt" ]; then OLD_DOCKER_TAG=$(cat $CACHE_DIR/old-docker-tag.txt); else OLD_DOCKER_TAG=$DOCKER_REPO_PROD; fi; echo "old docker tag = $OLD_DOCKER_TAG"
        - if docker pull $OLD_DOCKER_TAG; then _CACHE_FROM="--cache-from $OLD_DOCKER_TAG"; else _CACHE_FROM=""; fi
        # build new docker image
        - docker build -t local/viral-ngs:build $_CACHE_FROM .;
        # run tests using the docker image
        - travis/tests-docker.sh
        # deploy docker image
        - travis/deploy-docker.sh
        # version and validate WDL code
        - travis/version-wdl-runtimes.sh
        - travis/validate-wdl.sh
        # build DNAnexus pipelines and launch a few test executions
        - travis/build-dx.sh
        - travis/tests-dx.sh
        #- if [ "$TRAVIS_BRANCH" = "master" ]; then travis/tests-dx.sh; fi
        # test Cromwell local execution engine
        - travis/tests-cromwell.sh
      before_cache:
        - travis/list-docker-tags.sh | tail -1 > $CACHE_DIR/old-docker-tag.txt

    #- language: generic
    #  stage: build
    #  env:
    #    - TRAVIS_JOB=build_docker
    #    # DOCKER_USER
    #    - secure: hYX8492Wqpq3yqv+eHBV9c6VY8JlUSS8mUDfT1eWNEZF2vw8WrnTt8SrLIPC8etQUk1ZaSI/8XbJQKEr9LRqgvuO07AIv6BxYCg9l9BPHCj6B2YTTPo2qPkPapfvtGVd7PUZcWDUvzvPxJqMveuKVkTnCuuQSWwR68Y/Khxj8UY=
    #    # DOCKER_PASS
    #    - secure: QYylIMLvn1op6d//5yBD7KpquNxK/+xxQxIJLXWFgIl08sdT/MvrI6edgm3k8CumS7735eSV6C+KGOkF9JqM12aGUK/3PPckFGY+h/j4zQX26taT+6221ozbzF6hqYk6qm86FT5QVkBFLxsoDvt0Sh+1FPeVsWJf0o9yrLTrj2E=
    #  install: travis/upgrade-docker.sh
    #  script:
    #    - set -e
    #    - if [ -f "$CACHE_DIR/old-docker-tag.txt" ]; then OLD_DOCKER_TAG=$(cat $CACHE_DIR/old-docker-tag.txt); else OLD_DOCKER_TAG=$DOCKER_REPO_PROD; fi; echo "old docker tag = $OLD_DOCKER_TAG"
    #    - if docker pull $OLD_DOCKER_TAG; then _CACHE_FROM="--cache-from $OLD_DOCKER_TAG"; else _CACHE_FROM=""; fi
    #    - travis_wait docker build -t local/viral-ngs:build $_CACHE_FROM .;
    #    - travis/deploy-docker.sh
    #  before_cache:
    #    - travis/list-docker-tags.sh | tail -1 > $CACHE_DIR/old-docker-tag.txt
    #
    #- language: java
    #  jdk: openjdk8
    #  stage: build
    #  env:
    #    - TRAVIS_JOB=build_dxWDL
    #    # DX_API_TOKEN (for DNAnexus builds)
    #    - secure: "IPvLIQudIRyUl8iLNLujDig1afV+2v8AtRHpw0LsbL45xr0TvkmqjoHRmkYDnbdEeVdGC91ydLwfLNXcU/Cn7KRuIPE3InYX6VeomVO87aIXUzmmBCdFNGKd6o0u6Q/T+oJxemXwztW9XpKx3yT4RdLj7/zEpXnJm07/mKiquZE="
    #    - DX_PROJECT=project-F856jv809y3VkzyFGkKqX367
    #  install:
    #    - travis/install-wdl.sh
    #  script:
    #    - travis/version-wdl-runtimes.sh
    #    - travis/validate-wdl.sh
    #    - travis/build-dx.sh
    #- language: java
    #  jdk: openjdk8
    #  stage: test
    #  env:
    #    - TRAVIS_JOB=test_cromwell
    #  install:
    #    - DOCKER_TAG=`travis/list-docker-tags.sh | tail -1`
    #    - docker pull $DOCKER_TAG
    #    - travis/install-gatk.sh
    #    - travis/install-wdl.sh
    #  script:
    #    - travis/version-wdl-runtimes.sh
    #    - travis/validate-wdl.sh
    #    - travis/tests-cromwell.sh

    # - language: python
    #   sudo: false
    #   #stage: build
    #   env: TRAVIS_JOB=build_docs
    #   install: travis/install-pip-docs.sh
    #   script: travis/build-docs.sh

    # - language: python
    #   python: 3.6
    #   sudo: required
    #   #stage: test
    #   env:
    #     - TRAVIS_JOB=build_conda
    #     # $ANACONDA_TOKEN for uploading builds to anaconda.org ("notestaff" channel)
    #     - secure: "XwMC+g2gUeLmNPS+hB1n137Te8gV3RaGIEBX6GZrGdMkeISY7pKrF8U5Opl1C1C+hV4SoQjLcvpHMbE14J0rXnqvwnkRcdPo+EiLxOVjZozZaffeTI/2xQt49EXJrACtmzT4klbfIsP6W8L2zd3CgLij02Pkw36WjfPxbNkbqu8="

    #   install:
    #     - source travis/install-conda.sh
    #     - travis/install-conda-build.sh
    #   script:
    #     - travis/build-conda.sh
    #   before_cache:
    #     - conda clean --all --yes

    # - language: python
    #   python: 3.6
    #   #stage: test
    #   sudo: required
    #   env:
    #     - TRAVIS_JOB=test_py36
    #   before_install: travis/before_install.sh
    #   install:
    #     - source travis/install-conda.sh
    #     - travis/install-gatk.sh
    #     - travis/install-tools.sh
    #     - source travis/activate-conda.sh
    #   script:
    #     - travis/tests-long.sh
    #     - travis/tests-unit.sh
    #   after_success:
    #     - coveralls
    #   before_cache:
    #     - conda clean --all --yes

    # - language: python
    #   python: 3.6
    #   #stage: test
    #   sudo: required
    #   env:
    #     - TRAVIS_JOB=test_snakemake
    #   before_install: travis/before_install.sh
    #   install:
    #     - source travis/install-conda.sh
    #     - travis/install-gatk.sh
    #     - travis/install-tools.sh
    #     - source travis/activate-conda.sh
    #   script:
    #     - travis/tests-snakemake.sh
    #   after_success:
    #     - coveralls
    #   before_cache:
    #     - conda clean --all --yes

    #- language: python
    #  stage: test
    #  env:
    #    - TRAVIS_JOB=test_py36_in_docker
    #  install:
    #    - DOCKER_TAG=`travis/list-docker-tags.sh | tail -1`
    #    - docker pull $DOCKER_TAG
    #    - travis/install-gatk.sh
    #    - pip install coveralls==1.1
    #    - mkdir coverage
    #  script:
    #    - docker run -e _JAVA_OPTIONS -e PYTEST_ADDOPTS -v $GATK_PATH:/gatk -v coverage:/coverage --entrypoint /bin/bash $DOCKER_TAG -c 'set -e; cd /opt/viral-ngs/source; gatk3-register /gatk/GenomeAnalysisTK.jar; pytest test/integration test/unit; cp .coverage /coverage'
    #  after_success:
    #    - mv coverage/.coverage .
    #    - coveralls
    #
    #- language: generic
    #  stage: test
    #  env:
    #    - TRAVIS_JOB=build_conda_in_docker
    #    # $ANACONDA_TOKEN for uploading builds to anaconda.org ("broad-viral" channel)
    #    - secure: "cDKRuVUr2NMZk933RHMMYKDCfU2gZfe3VJLNG82zsj47rrfoRzUsDny71v27OuydgjICiBWGuFAl4alNBVkzQWGt7G1DaFVLn48SwqtnG4u0KAUVX32b/0sw7OrXRDDqD5pr5Q8J59xwxSKQmmXFXlMbZpSEeREf8c3Yn6pvm2c="
    #  install:
    #    - DOCKER_TAG=`travis/list-docker-tags.sh | tail -1`
    #    - docker pull $DOCKER_TAG
    #    - travis/install-gatk.sh
    #  script:
    #    - docker run -v $GATK_PATH:/gatk -e _JAVA_OPTIONS -e TRAVIS_BRANCH -e TRAVIS_PULL_REQUEST -e TRAVIS_TAG -e TRAVIS_COMMIT -e ANACONDA_TOKEN --entrypoint /bin/bash $DOCKER_TAG -c 'set -e; cd /opt/viral-ngs/source; gatk3-register /gatk/GenomeAnalysisTK.jar; travis/install-conda-build.sh; travis/build-conda.sh'

#        - os: osx
#          language: generic
#          stage: test
#          env:
#              - TRAVIS_JOB=test_osx
#              - TRAVIS_OSX_PYTHON_VERSION=py36
#              - TRAVIS_PYTHON_VERSION=3.6
#          before_install:
#              - travis/before_install.sh
#              # Under OSX, some versions of ruby seem to cause this error.
#              # See: https://github.com/travis-ci/travis-ci/issues/6307
#              - rvm get head
#          after_script:
#              # correct post-build failure on OSX due to non-zero exit code
#              - set +e
  
