# This file created by conda-build 2.1.1
# meta.yaml template originally from:
# /recipe_root, last modified Mon Jan 23 11:26:10 2017
# ------------------------------------------------

package:
    name: zlib
    version: 1.2.11
source:
    fn: zlib-1.2.11.tar.gz
    sha256: c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1
    url: http://zlib.net/zlib-1.2.11.tar.gz
build:
    features: ''
    number: '0'
    string: '0'
requirements:
    build: []
    run: []
test:
    commands:
        - test -f ${PREFIX}/lib/libz.a
        - conda inspect linkages -p ${PREFIX} zlib
about:
    home: http://zlib.net/
    license: zlib
    license_family: Other
    license_file: license.txt
    summary: Massively spiffy yet delicately unobtrusive compression library
extra:
    recipe-maintainers:
        - groutr
        - msarahan
        - ocefpaf
